#ifndef NEXUSCONFIG_GLOBAL_H
#define NEXUSCONFIG_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NEXUSCONFIG_LIBRARY)
#  define NEXUSCONFIGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NEXUSCONFIGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NEXUSCONFIG_GLOBAL_H
